language: python
python:
- 3.6.9
install: pip install -e .
script:
- pipenv install
deploy:
  provider: pypi
  username: creditas
  password:
    secure: QnPuKn+Dr7fvC1gOdSkLJt1VSeGcc2UhwW7rOXl0z4vXuOaXkJ7n8U0UEEYhNjSv2f1JLeHVZCevDPDuK71WAnwbT+gxJU/lf7abzKWp5lObucHKUfQZ5KzXRP8kbJQsnpzW2jq4Exqu63dv5tm80uI+FNHIE+pzj7PUtlUYTlVSluKsbroZ5cQKiGVmJ+RPcCgmeivAhi2yPPUTvBTvxOH5W1OyetfzVfgEhjnHrX++T4Ms8O7zue8yzAja9fE5V578yeuHsBVh7c3HRCiDd0FHEFq1jEv4UjtO6HteMvsspT0FqciTh80T1Ox5aNDQOkJC6evhio271PRZsfbvk8wDk3TuoZF3qSyuPxPnWl2c4EL6WUUEOWZESRe8+lmA7yvNcF5fA13V/SEOTb6eC9Be2nQ7TXH5z7kpri4b50sBaC5Nkpzbm9GNEhDep778HjKR2yx7axfUqnJMHDsSu4VlzMzV0XWO2A0a8ZVXn828W7vcoBr80QZ8wlUwMHSzbr225J9AzgmPxfCPpYN4ss9Kca8VpeN6YNRgJUYFmXSu5uG+2f/DdwbSYMB955kWTM8Kx7ikGJXtBU0l2+flLFJnod4HDv6SITT7F8z0tJMQOpkEmjCA3a7gITIpxstDj+zSauTGsnK6JtKWWIqRYDyD45DwQ9xF5awklozYOTE=
  on:
    branch: main
