language: python
python:
- 3.6.9
install: pip install -e .
script:
- pipenv install
deploy:
  provider: pypi
  username: creditas
  password:
    secure: YHJwMNKWQDDyNTMOANJkXdIMsFd/FxmrK64MOckEPNydOKcs7Lxh7X6EolXWTjrtlNZfyCk7xVhLLcHNg9h8SSil/NqTFl3zgkP+tUlxU/u5pZxcLKeeXT/lFwkkpk2NqIWUKI+vHW0cJ00uBTIpVvb6jbSWPm3dYRrbJlKTPD/BNXckIYxSZwgqVmIPOxc28iCAmE1v1zIh352eEzMVazrrVAP+s3Pik8wpBFylORgaPzLhx1Z6pl6rDE68OolK/nrlWeNHC4HGtDukaQ5XpVgBKkWUuqZgkjHCV179RqyF86or/ZhcKa2ls4B/IQeGqczrKF5j6BIBXhQV9hfaZ6swz935js0QL8csmKSuVaAPhxG5xGxqE2UFij4zZT1TVKDg8PQmPMMCvdf+s7ZLw3dio5BTD2FW5XsvBeYIBlYuKRWslDaZZ2g+k6YpWQYJc0t5PQQnMOPhfm9zh+8bs8hval1pkGnIk9powIwEdIDxLKNnXhJFcokk7i6LvxlRfVEtlId36FHKQKFgjLQPSpxv3O4ef+UW6NintEqbTWDisrWNdW1U/vChJYIa8jW66hCXy2m1jURT7Pi27mHZd1Qlz8QmnoPIQtE2h5SenBXDHgDVAM8aGSnQpXbfTb57rSxDdJVLNZ0sKxEuMXkZcLCucmQ8I2IeQcJWmhLJTbw=
  on:
    branch: main
