version: 2
jobs:
  upload_pipy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = creditas" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            pip install wheel
            python setup.py bdist_wheel
            twine upload dist/*

workflows:
  version: 2
  deploy_schemas:
    jobs:
      - upload_pipy:
          filters:
            branches:
              only:
                - test
